### ISSUE TITLE
line-hight垂直居中需要overflow:hidden?

### ISSUE THREAD

**Issue by cycold** [icewaters/icewaters.github.io#13]
参考: http://www.blueidea.com/tech/web/2006/3231.asp

``` css
.middle-demo-1{
    height: 4em;
    line-height: 4em;
    overflow: hidden;
}
```

> 要注意的是：
> 1. 使用相对高度定义你的 height 和 line-height
> 2. 不想毁了你的布局的话，overflow: hidden 一定要
