### ISSUE TITLE
css3-transform

### ISSUE THREAD

**Issue by cycold** [icewaters/icewaters.github.io#2]
**css3 transform学习**
css3的transform功能可以用来实现元素(文字或者图像)的 **旋转**  **缩放** **倾斜** **移动**  **矩阵**
通过transform属性的形式实现transform功能,目前还需要加上浏览器的前缀.

**一下都是基于2d 形变的**

旋转:

``` css
div{
  -webkit-transform: rotate(45deg);
}
```

> `rotate(45deg)`是使元素顺时针旋转45度
> 注意这里的单位:**deg**是css3的"values and units"模块中定义的角度单位.

缩放

``` css
div{
   -webkit-transform: scale(0.5,2);
   -webkit-transform: scaleX(0.5);
   -webkit-transform: scaleY(0.5);
}
```

> `scale(0.5,2)`中的参数表示要缩放的倍率.(水平方向缩小50%,垂直方向放大一倍).
> `scaleX(0.5)`水平方向缩小50%
> `scaleY(0.5)`垂直方向缩小50%
> 如果只传入一个参数,表示水平和垂直缩放倍率相同.

倾斜

``` css
div{
   -webkit-transform: skew(30deg,45deg);
   -webkit-transform: skewX(30deg);
   -webkit-transform: skewY(45deg);
}
```

> `skew(35deg, 45deg)`表示水平方向倾斜30度,垂直方向倾斜45度.
> `skewX(30deg)`沿着X轴斜切30度
> `skewY(45deg)`沿着Y轴斜切45度
> 如果只传入一个参数,表示只在水平方向上进行倾斜,垂直方向上不做倾斜.

移动

``` css
div{
   /*水平方向上移动50px, 垂直方向上移动50px*/
   -webkit-transform: translate(50px,50px);
   /*水平方向上移动50px, 垂直方向上不移动*/
   -webkit-transform: translate(50px);
   /*只移动水平方向*/
   -webkit-transform: translateX(50px);
   /*只移动垂直方向*/
   -webkit-transform: translateY(50px);
}
```

> 注意以上`translateX`和`translateY`不能同时存在,后面的值会覆盖前面的值,要想同时移动x和y方向,
> 请使用`translate(x,y)`
> 
> ``` css
> div{
>     /*这里并不会同时移动Y方向100px,再移动x方向-50px,最后的结果是只移动了x方向*/
>     -webkit-transform: translateY(100px);
>     -webkit-transform: translateX(-50px);
> }
> ```

**transform多个属性同时变化** 注意属性顺序不同会导致变形结果不同

> 注意对比两段代码的不同
> 
> ``` css
> div{
>   /*先移动,后旋转,然后缩放*/
>    -webkit-transform: translate(200px,100px) rotate(45deg) scale(1.5);
> }
> div{
>   /*先旋转,后缩放,然后移动*/
>    -webkit-transform: rotate(45deg) scale(1.5) translate(200px,100px);
> }
> ```

第一段代码变形处理
 1)向右移动200px,向下移动100px,
![image](https://cloud.githubusercontent.com/assets/2446601/5057654/f441d91c-6d08-11e4-8cd9-d3c9c9747bf4.png)
 2)然后旋转45度,并且放大1.5倍

![image](https://cloud.githubusercontent.com/assets/2446601/5057652/d9fca622-6d08-11e4-81f9-8110aaba5282.png)

第二段代码变形处理
 1)首先旋转45度,放大1.5倍
![image](https://cloud.githubusercontent.com/assets/2446601/5057682/90df026c-6d0a-11e4-9817-92dee4b11563.png)

 2)然后向右移动200px,向下移动100px
![image](https://cloud.githubusercontent.com/assets/2446601/5057683/9aec6cae-6d0a-11e4-973e-44173583276c.png)

**改变元素变形的基准点**

> 元素默认变形的基准点:元素的中心点.使用`-webkit-transform-origin`可以改变元素的变形时的基准点.
> - 对比更改基准点前后的变化
> 
> ```
> /*修改变形基准点*/
> -webkit-transform-origin: left bottom;
> ```
> 
> ![image](https://cloud.githubusercontent.com/assets/2446601/5057702/6c3354ee-6d0b-11e4-8962-30e0495a6d64.png)
> 
> `-webkit-transform-origin`属性值分为:
> 水平方向的基准点,可以指定的值(left, center, right)
> 垂直方向的基准点,可以指定的值(top, center, bottom)
> 属性值其实还可以是百分比,比如: `transform-origin: 20% 20%;`

矩阵

> `transform: matrix(1.678, -0.256, 1.522, 2.333, -51.533, -1.989);`
> 它基本上能让你将若干变形效果（scale、rotate、skew等等）组合成单个声明
> 要完全理解矩阵你得了解相关的数学知识：
> http://www.w3.org/TR/css3-2d-transforms/#cssmatrix-interface
> 如果你的数学也不太好，我建议你访问这里：http://www.useragentman.com/matrix/

更多的了解css3的transform:http://www.w3.org/TR/css3-transforms/
